/**
 * Copies assets/ into the package (icons/ + metadata.json) and generates
 * the typed slug/style unions in src/emoji.generated.ts.
 */
import fs from 'node:fs';
import path from 'node:path';

const PKG = import.meta.dirname;
const ASSETS = path.resolve(PKG, '../../assets');

const metadata = JSON.parse(
  fs.readFileSync(path.join(ASSETS, 'metadata.json'), 'utf8'),
) as {styles: string[]; emojis: {slug: string}[]};

fs.rmSync(path.join(PKG, 'icons'), {recursive: true, force: true});
for (const style of metadata.styles) {
  fs.cpSync(path.join(ASSETS, style), path.join(PKG, 'icons', style), {
    recursive: true,
  });
}
fs.copyFileSync(
  path.join(ASSETS, 'metadata.json'),
  path.join(PKG, 'metadata.json'),
);

const union = (values: string[]): string =>
  values.map((v) => `  | '${v}'`).join('\n');

fs.writeFileSync(
  path.join(PKG, 'src/emoji.generated.ts'),
  `// Generated by build.ts — do not edit.
export type EmojiStyle =
${union(metadata.styles)};

export type EmojiSlug =
${union(metadata.emojis.map((e) => e.slug))};
`,
);
console.log(
  `@fluentui-emoji/svg: ${metadata.emojis.length} emojis, ${metadata.styles.length} styles`,
);
